version: '3.3'
services:
   sonarqube:
      image: sonarqube:8.9-developer
      command: "-Dsonar.search.javaAdditionalOpts=-Dnode.store.allow_mmap=false"
      ports:
         - "9000:9000"
      volumes:
         - sonarqube-conf:/opt/sonarqube/conf
         - sonarqube-data:/opt/sonarqube/data
         - sonarqube-extensions:/opt/sonarqube/extensions
         - sonarqube-bundled-plugins:/opt/sonarqube/lib/bundled-plugins
         - sonarqube-logs:/opt/sonarqube/logs
volumes:
   sonarqube-conf:
      external: true
   sonarqube-data:
      external: true
   sonarqube-extensions:
      external: true
   sonarqube-bundled-plugins:
      external: true
   sonarqube-logs:
      external: true
